sudo: false
cache: pip

language: python

python:
  - 3.6

env:
  matrix:
    - TOXENV=rst-lint
    - TOXENV=manifest
    - TOXENV=docs
    - TOXENV=py

install:
  - pip install tox

script:
  - tox

notifications:
  slack: pybel:n2KbWKBum3musnBg3L76gGwq
